language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - swig
cache:
  directories:

before_install:
  # ========== Point apt-get to C++11-compatible compiler ==========
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # ============== Handle Python third-party packages ==============
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy h5py pandas matplotlib pil
  - source activate test-environment

install:
  # ================= Get C++11-compatible compiler ==================
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

script:
  - cd tests
  - ./travis.sh
  - cat LastTest_normal-gcc.log
  - cd ..