language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - swig
env:
  global:
    - COVERALLS_PARALLEL=true
cache:
  directories:
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
before_install:
  # ========== Point apt-get to C++11-compatible compiler =====================
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # ============== Handle Python third-party packages =========================
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  #- conda update -q --force conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy h5py pandas matplotlib pillow
  - source activate test-environment
  - pip install coverage
  - pip install cpp-coveralls
  - pip install coveralls

install:
  # ================= Get C++11 and MPI-compatible compiler ===================
  #- sudo apt-get install -qq gcc-6 g++-6
  - sudo apt-get install swig
  #- sudo rm /usr/bin/gcc
  #- sudo rm /usr/bin/g++
  #- sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc
  #- sudo ln -s /usr/bin/g++-6 /usr/bin/g++
  - conda config --add channels conda-forge
  - conda install mpi4py openmpi-mpicc openmpi-mpicxx
  - export LD_PRELOAD="$HOME/miniconda/envs/test-environment/lib/libmpi_cxx.so"

script:
  - cd tests
  - ./travis.sh

after_success:
  - cd ..
  - cpp-coveralls -i src -i build/temp.linux*/src/ --exclude-pattern "/usr/*" --dump cpp_cov.json
  - cp tests/.coverage ./
  # Switch to Python version, which can merge reports
  - coveralls --rcfile=./tests/.coveragerc --merge=cpp_cov.json
